# Generated by Django 4.0 on 2022-05-28 09:12

import django.db.models.deletion
from django.db import migrations, models

import generated_columns.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DomainWhitelist",
            fields=[
                (
                    "domain",
                    models.CharField(max_length=254, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Squared",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operand", models.IntegerField()),
                (
                    "result",
                    generated_columns.models.GeneratedIntegerField(
                        expression="operand * operand"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "email_domain",
                    generated_columns.models.DomainForeignKey(
                        expression="substring(email from '@(.*)$')",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="generated_columns.domainwhitelist",
                    ),
                ),
            ],
        ),
    ]
